### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by pump61** [Bunnky/IDreamOfEasy#2]
## Description (Required)
Plugin error on startup

## Steps to reproduce the Issue (Required)
put the plugin in the server plugins and start the server

## Expected behavior (Required)
the plugin works

## Server Log / Error Report
[12:55:11] [Server thread/INFO]: [IDreamOfEasy] Enabling IDreamOfEasy vDev - 2
[12:55:11] [Server thread/INFO]: [IDreamOfEasy]  ┳  ┳┓┳┓┏┓┏┓┳┳┓  ┏┓┏┓  ┏┓┏┓┏┓┓┏ 
[12:55:11] [Server thread/INFO]: [IDreamOfEasy]  ┃  ┃┃┣┫┣ ┣┫┃┃┃  ┃┃┣   ┣ ┣┫┗┓┗┫ 
[12:55:11] [Server thread/INFO]: [IDreamOfEasy]  ┻  ┻┛┛┗┗┛┛┗┛ ┗  ┗┛┻   ┗┛┛┗┗┛┗┛ 
[12:55:11] [Server thread/INFO]: [IDreamOfEasy]         IDOE by Bunnky          
[12:55:11] [Timer-1/INFO]: [io.github.xanthic.cache.core.CacheApiSettings] Xanthic: Automatically set default cache provider to CaffeineProvider.
[12:55:11] [Server thread/ERROR]: Error occurred while enabling IDreamOfEasy vDev - 2 (Is it up to date?)
java.lang.NoSuchFieldError: Class org.bukkit.entity.EntityType does not have member field 'org.bukkit.entity.EntityType ARMADILLO'
	at me.bunnky.idreamofeasy.utils.IDOEUtility.createEntityDropMap(IDOEUtility.java:73) ~[IDreamOfEasy.jar:?]
	at me.bunnky.idreamofeasy.utils.IDOEUtility.<clinit>(IDOEUtility.java:29) ~[IDreamOfEasy.jar:?]
	at me.bunnky.idreamofeasy.slimefun.machines.PlayerHopper.<init>(PlayerHopper.java:45) ~[IDreamOfEasy.jar:?]
	at me.bunnky.idreamofeasy.slimefun.setup.Setup.setup(Setup.java:726) ~[IDreamOfEasy.jar:?]
	at me.bunnky.idreamofeasy.IDreamOfEasy.onEnable(IDreamOfEasy.java:45) ~[IDreamOfEasy.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:55:11] [Server thread/INFO]: [IDreamOfEasy] Disabling IDreamOfEasy vDev - 2

[13:08:14 INFO]: This Server uses the following setup of Slimefun:
[13:08:14 INFO]: Purpur git-Purpur-2176 (MC: 1.20.4)
[13:08:14 INFO]: Slimefun Dev - 1156
[13:08:14 INFO]: Metrics-Module #29
[13:08:14 INFO]: Java 21
[13:08:14 INFO]: 
[13:08:14 INFO]: Installed Addons: (28)
[13:08:14 INFO]:   Networks vDev - 4
[13:08:14 INFO]:   AuraSkills v2.2.4
[13:08:14 INFO]:   ShopGUIPlus v1.97.0
[13:08:14 INFO]:   ExtraTools vDEV - 36 (git 922c0324)
[13:08:14 INFO]:   FoxyMachines vDev - 68
[13:08:14 INFO]:   FNAmplifications vDev - 105
[13:08:14 INFO]:   SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)
[13:08:14 INFO]:   DynaTech v1.0.0
[13:08:14 INFO]:   AdvancedEnchantments v9.11.5
[13:08:14 INFO]:   VillagerTrade vDev - 6
[13:08:14 INFO]:   ExtraGear vDEV - 13 (git c62047e2)
[13:08:14 INFO]:   SlimeHUD vDEV - 11 (git b6dc2d53)
[13:08:14 INFO]:   IDreamOfEasy vDev - 2
[13:08:14 INFO]:   InfinityExpansion vMODIFIED
[13:08:14 INFO]:   Supreme vMODIFIED
[13:08:14 INFO]:   RedProtect v8.1.1-SNAPSHOT
[13:08:14 INFO]:   SlimyTreeTaps vDEV - 20 (git 963f0383)
[13:08:14 INFO]:   MobCapturer vDEV - 33 (git 6fc26c35)
[13:08:14 INFO]:   FlowerPower vDev - 2
[13:08:14 INFO]:   GeneticChickengineering vDev - 13
[13:08:14 INFO]:   FluffyMachines vDev - 8
[13:08:14 INFO]:   SlimeFrame v1.6.2
[13:08:14 INFO]:   Cultivation vDEV - 11 (git 3e25165d)
[13:08:14 INFO]:   FastMachines vDev - 34
[13:08:14 INFO]:   Vouchers v1.0.0
[13:08:14 INFO]:   ExtraUtilities v1.0.1
[13:08:14 INFO]:   SimpleUtils vDEV - 15 (git 4250fd5e)
[13:08:14 INFO]:   WorldEditSlimefun vDev - 7

**Comment by Bunnky** [comment]
IDOE only supports latest Slimefun, which is 1.20.6
